# Generated by Django 3.2.22 on 2023-10-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideaboard', '0007_auto_20231025_0618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='summary',
        ),
    ]
