# Generated by Django 3.2.22 on 2023-10-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideaboard', '0003_auto_20231023_0503'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('summary', models.CharField(max_length=100)),
                ('keyword', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, upload_to='post_pics')),
                ('image2', models.ImageField(blank=True, upload_to='post_pics')),
                ('image3', models.ImageField(blank=True, upload_to='post_pics')),
                ('content', models.TextField()),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='idea_post',
        ),
    ]
